version: "3"
services:
 app:
   build: ./app
   ports:
     - "5000:80"
 test:
   build: ./testing
   environment:
     - PYTHONPATH=/system-engineer/app:/system-engineer/testing:/system-engineer
   depends_on:
     - app
   ports:
     - "50001:80"   

