version: "3"
services:
 app:
   build: app
   ports:
     - "5000:5000"
 test:
   build: testing
   environment:
     - PYTHONPATH=/system-engineer/app
   depends_on:
     - app
   links:
     - app
   ports:
     - "5001:5001"   

